# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd5e235f805d39e0e8a9ed5d159d110f37b748a46cb0333b3240e110ce4d0ca9a31a034f73bd1b6156c7579798e0544e7ab381b24bea01c988dcece2a3663857

test:
  secret_key_base: 2d1fef5f8bfa41903c639e694612a1e37dd342afd20f022555c0a3d1126f23283bfc4fbd4d6c4ebf1709d2baebd3704175735d9466404b3892a49e9ed88149d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
